# Generated by Django 4.0.5 on 2022-07-11 23:33

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone
import happyrabbit.abc.external_account as external_account


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('external_service', models.CharField(choices=[('TELEGRAM', 'Telegram')], max_length=200)),
                ('external_user_id', models.IntegerField(blank=True, default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=(external_account.ExternalAccount, models.Model),
        ),
        migrations.CreateModel(
            name='AuthTokenModel',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'hr_user_auth_token',
            },
            bases=(external_account.AuthToken, models.Model),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user_profile_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=200)),
                ('last_name', models.CharField(blank=True, max_length=200)),
                ('language_code', models.CharField(blank=True, max_length=2)),
                ('username', models.CharField(max_length=200)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hr_user.account')),
            ],
            bases=(models.Model, external_account.ExternalUserProfile),
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('session_id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('date_logged_in', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date logged in')),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hr_user.account')),
                ('auth_token', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr_user.authtokenmodel')),
            ],
            bases=(external_account.ExternalSession, models.Model),
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('child_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('carrots', models.IntegerField(default=0)),
                ('guardian_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
