# Generated by Django 4.0.5 on 2022-07-03 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr_user', '0002_auto_20220624_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='external_service',
            field=models.CharField(choices=[('TELEGRAM', 'Telegram')], max_length=200),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hr_user.account'),
        ),
    ]
