# Generated by Django 4.0.5 on 2022-07-16 20:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hr_user', '0003_rename_guardian_id_child_guardian'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Child',
            new_name='ChildModel',
        ),
    ]
