# Generated by Django 3.2.13 on 2022-07-09 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_user', '0003_alter_account_external_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='external_user_id',
            field=models.IntegerField(blank=True),
        ),
    ]
