# Generated by Django 4.0.5 on 2022-07-08 22:30

from django.db import migrations, models
import django.utils.timezone
import happyrabbit.hr_user.abstract


class Migration(migrations.Migration):

    dependencies = [
        ('hr_user', '0003_alter_account_external_service_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('session_id', models.IntegerField(primary_key=True, serialize=False)),
                ('date_logged_in', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date logged in')),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hr_user.account')),
            ],
            bases=(happyrabbit.hr_user.abstract.ExternalSession, models.Model),
        ),
    ]
