# Generated by Django 4.0.5 on 2022-07-17 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr_user', '0002_auto_20220717_1205'),
        ('hr_user', '0004_rename_child_childmodel'),
    ]

    operations = [
    ]
