# Generated by Django 4.0.5 on 2022-07-09 05:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import happyrabbit.hr_user.abstract


class Migration(migrations.Migration):

    dependencies = [
        ('hr_user', '0004_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthTokenModel',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'hr_user_auth_token',
            },
            bases=(happyrabbit.hr_user.abstract.AuthToken, models.Model),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_id',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='session',
            name='auth_token',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr_user.authtokenmodel'),
        ),
    ]
