# Generated by Django 3.2.13 on 2022-07-10 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_user', '0005_alter_account_account_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='child_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_profile_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
