# Generated by Django 3.2.13 on 2022-07-11 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_user', '0006_auto_20220710_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='external_user_id',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
