# Generated by Django 4.0.5 on 2022-07-24 03:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import happyrabbit.abc.tracking
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr_user', '0005_merge_20220717_1945'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityEventModel',
            fields=[
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.JSONField(null=True)),
                ('activity', models.JSONField()),
                ('duration', models.PositiveIntegerField(help_text='Duration in minutes', null=True)),
                ('carrots', models.PositiveIntegerField(help_text='Earned carrots')),
                ('time_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr_user.childmodel')),
            ],
            options={
                'verbose_name': 'Activity Event',
                'verbose_name_plural': 'Activity Events',
                'db_table': 'tracking_activity_event',
            },
            bases=(happyrabbit.abc.tracking.ActivityEvent, models.Model),
        ),
    ]
