# Generated by Django 4.0.5 on 2022-08-05 01:39

from django.db import migrations, models
import happyrabbit.abc.json.encoders


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityeventmodel',
            name='activity',
            field=models.JSONField(decoder=happyrabbit.abc.json.encoders.DjangoModelJSONDecoder, encoder=happyrabbit.abc.json.encoders.DjangoModelJSONEncoder),
        ),
        migrations.AlterField(
            model_name='activityeventmodel',
            name='category',
            field=models.JSONField(decoder=happyrabbit.abc.json.encoders.DjangoModelJSONDecoder, encoder=happyrabbit.abc.json.encoders.DjangoModelJSONEncoder, null=True),
        ),
    ]
