# Generated by Django 4.0.5 on 2022-08-14 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='activitymodel',
            table='activity',
        ),
        migrations.AlterModelTable(
            name='categorymodel',
            table='activity_category',
        ),
    ]
