# Generated by Django 4.0.5 on 2022-07-19 01:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activity', '0002_auto_20220717_1410'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Activity',
            new_name='ActivityModel',
        ),
        migrations.AlterModelTable(
            name='activitymodel',
            table='hr_user_category',
        ),
    ]
