# Generated by Django 4.0.5 on 2022-07-20 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_rename_activity_activitymodel_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitymodel',
            options={'verbose_name': 'Activity', 'verbose_name_plural': 'Activities'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='rewardrule',
            options={'verbose_name': 'Reward Rule', 'verbose_name_plural': 'Reward Rules'},
        ),
    ]
